### Site metadata ###

site_name: MkDocs Quickstart

### Build settings ###

theme: readthedocs

nav:
  - Home: index.md
  - About MkDocs: about-mkdocs.md
  - Tutorial:
      - TL;DR: tutorial/tldr.md
      - Installation: tutorial/installation.md
      - Set up project: tutorial/setup-project.md
      - Advanced: tutorial/advanced.md
      - Usage: tutorial/usage.md
      - Deploy: tutorial/deploy.md
